class data:
    def __init__( self ):
        
        self.deklinationen = {
            "A-Deklination": {
                "nominativ_singular": "puella",
                "genitiv_singular": "puellae",
                "dativ_singular": "puellae",
                "akkusativ_singular": "puellam",
                "ablativ_singular": "puella",
                "nominativ_plural": "puellae",
                "genitiv_plural": "puellarum",
                "dativ_plural": "puellis",
                "akkusativ_plural": "puellas",
                "ablativ_plural": "puellis",
            },
    
            "O-Deklination": {
                "nominativ_singular": "dominus",
                "genitiv_singular": "domini",
                "dativ_singular": "domino",
                "akkusativ_singular": "dominum",
                "ablativ_singular": "domino",
                "nominativ_plural": "domini",
                "genitiv_plural": "dominorum",
                "dativ_plural": "dominis",
                "akkusativ_plural": "dominos",
                "ablativ_plural": "dominis",
            },
    
            "O-Deklination Neutrum": {
                "nominativ_singular": "bellum",
                "genitiv_singular": "belli",
                "dativ_singular": "bello",
                "akkusativ_singular": "bellum",
                "ablativ_singular": "bello",
                "nominativ_plural": "bella",
                "genitiv_plural": "bellorum",
                "dativ_plural": "bellis",
                "akkusativ_plural": "bella",
                "ablativ_plural": "bellis",
            },
    
            "Konsonantische Deklination": {
                "nominativ_singular": "rex",
                "genitiv_singular": "regis",
                "dativ_singular": "regi",
                "akkusativ_singular": "regem",
                "ablativ_singular": "rege",
                "nominativ_plural": "reges",
                "genitiv_plural": "regum",
                "dativ_plural": "regibus",
                "akkusativ_plural": "reges",
                "ablativ_plural": "regibus",
            },
    
            "Konsonantische Deklination Neutrum": {
                "nominativ_singular": "corpus",
                "genitiv_singular": "corporis",
                "dativ_singular": "corpori",
                "akkusativ_singular": "corpus",
                "ablativ_singular": "corpore",
                "nominativ_plural": "corpora",
                "genitiv_plural": "corporum",
                "dativ_plural": "corporibus",
                "akkusativ_plural": "corpora",
                "ablativ_plural": "corporibus",
            },
            "Konsonantische Deklination Neutrum mit Genitiv Plural -ium": {
                "nominativ_singular": "animal",
                "genitiv_singular": "animalis",
                "dativ_singular": "animali",
                "akkusativ_singular": "animal",
                "ablativ_singular": "animali",
                "nominativ_plural": "animalia",
                "genitiv_plural": "animalium",
                "dativ_plural": "animalibus",
                "akkusativ_plural": "animalia",
                "ablativ_plural": "animalibus",
            },
    
            "I-Deklination": {
                "nominativ_singular": "civis",
                "genitiv_singular": "civis",
                "dativ_singular": "civi",
                "akkusativ_singular": "civem",
                "ablativ_singular": "cive",
                "nominativ_plural": "cives",
                "genitiv_plural": "civium",
                "dativ_plural": "civibus",
                "akkusativ_plural": "cives",
                "ablativ_plural": "civibus",
            },
    
            "I-Deklination Neutrum": {
                "nominativ_singular": "mare",
                "genitiv_singular": "maris",
                "dativ_singular": "mari",
                "akkusativ_singular": "mare",
                "ablativ_singular": "mari",
                "nominativ_plural": "maria",
                "genitiv_plural": "marium",
                "dativ_plural": "maribus",
                "akkusativ_plural": "maria",
                "ablativ_plural": "maribus",
            },
    
            "U-Deklination": {
                "nominativ_singular": "manus",
                "genitiv_singular": "manus",
                "dativ_singular": "manui",
                "akkusativ_singular": "manum",
                "ablativ_singular": "manu",
                "nominativ_plural": "manus",
                "genitiv_plural": "manuum",
                "dativ_plural": "manibus",
                "akkusativ_plural": "manus",
                "ablativ_plural": "manibus",
            },
    
            "E-Deklination": {
                "nominativ_singular": "res",
                "genitiv_singular": "rei",
                "dativ_singular": "rei",
                "akkusativ_singular": "rem",
                "ablativ_singular": "re",
                "nominativ_plural": "res",
                "genitiv_plural": "rerum",
                "dativ_plural": "rebus",
                "akkusativ_plural": "res",
                "ablativ_plural": "rebus",
            },
        }

        self.conjugations = {
            "a-Konjugation-present": {
                "1st_singular": "amo",
                "2nd_singular": "amas",
                "3rd_singular": "amat",
                "1st_plural": "amamus",
                "2nd_plural": "amatis",
                "3rd_plural": "amant",
            },
            "a-Konjugation-past": {
                "1st_singular": "amavi",
                "2nd_singular": "amavisti",
                "3rd_singular": "amavit",
                "1st_plural": "amavimus",
                "2nd_plural": "amavistis",
                "3rd_plural": "amaverunt",
            },
            "a-Konjugation-perfect": {
                "1st_singular": "amaveram",
                "2nd_singular": "amaveras",
                "3rd_singular": "amaverat",
                "1st_plural": "amaveramus",
                "2nd_plural": "amaveratis",
                "3rd_plural": "amaverant",
            },
            "a-Konjugation-pluperfect": {
                "1st_singular": "amavero",
                "2nd_singular": "amaveris",
                "3rd_singular": "amaverit",
                "1st_plural": "amaverimus",
                "2nd_plural": "amaveritis",
                "3rd_plural": "amaverint",
            },
            "a-Konjugation-present-passive": {
                "1st_singular": "amor",
                "2nd_singular": "amaris",
                "3rd_singular": "amatur",
                "1st_plural": "amamur",
                "2nd_plural": "amamini",
                "3rd_plural": "amantur",
            },
            "a-Konjugation-past-passive": {
                "1st_singular": "amatus sum",
                "2nd_singular": "amatus es",
                "3rd_singular": "amatus est",
                "1st_plural": "amati sumus",
                "2nd_plural": "amati estis",
                "3rd_plural": "amati sunt",
            },
            "a-Konjugation-perfect-passive": {
                "1st_singular": "amatus eram",
                "2nd_singular": "amatus eras",
                "3rd_singular": "amatus erat",
                "1st_plural": "amati eramus",
                "2nd_plural": "amati eratis",
                "3rd_plural": "amati erant",
            },
            "a-Konjugation-pluperfect-passive": {
                "1st_singular": "amatus ero",
                "2nd_singular": "amatus eris",
                "3rd_singular": "amatus erit",
                "1st_plural": "amati erimus",
                "2nd_plural": "amati eritis",
                "3rd_plural": "amati erunt",
            },
            "e-Konjugation-present": {
                "1st_singular": "moneo",
                "2nd_singular": "mones",
                "3rd_singular": "monet",
                "1st_plural": "monemus",
                "2nd_plural": "monetis",
                "3rd_plural": "monent",
            },
            "e-Konjugation-past": {
                "1st_singular": "monui",
                "2nd_singular": "monuisti",
                "3rd_singular": "monuit",
                "1st_plural": "monuimus",
                "2nd_plural": "monuistis",
                "3rd_plural": "monuerunt",
            },
            "e-Konjugation-perfect": {
                "1st_singular": "monueram",
                "2nd_singular": "monueras",
                "3rd_singular": "monuerat",
                "1st_plural": "monueramus",
                "2nd_plural": "monueratis",
                "3rd_plural": "monuerant",
            },
            "e-Konjugation-pluperfect": {
                "1st_singular": "monuero",
                "2nd_singular": "monueris",
                "3rd_singular": "monuerit",
                "1st_plural": "monuerimus",
                "2nd_plural": "monueritis",
                "3rd_plural": "monuerint",
            },
            "e-Konjugation-present-passive": {
                "1st_singular": "moneor",
                "2nd_singular": "moneris",
                "3rd_singular": "monetur",
                "1st_plural": "monemur",
                "2nd_plural": "monemini",
                "3rd_plural": "monentur",
            },
            "e-Konjugation-past-passive": {
                "1st_singular": "monitus sum",
                "2nd_singular": "monitus es",
                "3rd_singular": "monitus est",
                "1st_plural": "moniti sumus",
                "2nd_plural": "moniti estis",
                "3rd_plural": "moniti sunt",
            },
            "e-Konjugation-perfect-passive": {
                "1st_singular": "monitus eram",
                "2nd_singular": "monitus eras",
                "3rd_singular": "monitus erat",
                "1st_plural": "moniti eramus",
                "2nd_plural": "moniti eratis",
                "3rd_plural": "moniti erant",
            },
            "e-Konjugation-pluperfect-passive": {
                "1st_singular": "monitus ero",
                "2nd_singular": "monitus eris",
                "3rd_singular": "monitus erit",
                "1st_plural": "moniti erimus",
                "2nd_plural": "moniti eritis",
                "3rd_plural": "moniti erunt",
            },
            "i-Konjugation-present": {
                "1st_singular": "audio",
                "2nd_singular": "audis",
                "3rd_singular": "audit",
                "1st_plural": "audimus",
                "2nd_plural": "auditis",
                "3rd_plural": "audiunt",
            },
            "i-Konjugation-past": {
                "1st_singular": "audivi",
                "2nd_singular": "audivisti",
                "3rd_singular": "audivit",
                "1st_plural": "audivimus",
                "2nd_plural": "audivistis",
                "3rd_plural": "audiverunt",
            },
            "i-Konjugation-perfect": {
                "1st_singular": "audiveram",
                "2nd_singular": "audiveras",
                "3rd_singular": "audiverat",
                "1st_plural": "audiveramus",
                "2nd_plural": "audiveratis",
                "3rd_plural": "audiverant",
            },
            "i-Konjugation-pluperfect": {
                "1st_singular": "audivero",
                "2nd_singular": "audiveris",
                "3rd_singular": "audiverit",
                "1st_plural": "audiverimus",
                "2nd_plural": "audiveritis",
                "3rd_plural": "audiverint",
            },
            "i-Konjugation-present-passive": {
                "1st_singular": "audior",
                "2nd_singular": "audiris",
                "3rd_singular": "auditur",
                "1st_plural": "audimur",
                "2nd_plural": "audimini",
                "3rd_plural": "audiuntur",
            },
            "i-Konjugation-past-passive": {
                "1st_singular": "auditus sum",
                "2nd_singular": "auditus es",
                "3rd_singular": "auditus est",
                "1st_plural": "auditi sumus",
                "2nd_plural": "auditi estis",
                "3rd_plural": "auditi sunt",
            },
            "i-Konjugation-perfect-passive": {
                "1st_singular": "auditus eram",
                "2nd_singular": "auditus eras",
                "3rd_singular": "auditus erat",
                "1st_plural": "auditi eramus",
                "2nd_plural": "auditi eratis",
                "3rd_plural": "auditi erant",
            },
            "i-Konjugation-pluperfect-passive": {
                "1st_singular": "auditus ero",
                "2nd_singular": "auditus eris",
                "3rd_singular": "auditus erit",
                "1st_plural": "auditi erimus",
                "2nd_plural": "auditi eritis",
                "3rd_plural": "auditi erunt",
            },
            "konsonantische Konjugation-present": {
                "1st_singular": "rego",
                "2nd_singular": "regis",
                "3rd_singular": "regit",
                "1st_plural": "regimus",
                "2nd_plural": "regitis",
                "3rd_plural": "regunt",
            },
            "konsonantische Konjugation-past": {
                "1st_singular": "rexi",
                "2nd_singular": "rexisti",
                "3rd_singular": "rexit",
                "1st_plural": "reximus",
                "2nd_plural": "rexistis",
                "3rd_plural": "rexerunt",
            },
            "konsonantische Konjugation-perfect": {
                "1st_singular": "rexeram",
                "2nd_singular": "rexeras",
                "3rd_singular": "rexerat",
                "1st_plural": "rexeramus",
                "2nd_plural": "rexeratis",
                "3rd_plural": "rexerant",
            },
            "konsonantische Konjugation-pluperfect": {
                "1st_singular": "rexero",
                "2nd_singular": "rexeris",
                "3rd_singular": "rexerit",
                "1st_plural": "rexerimus",
                "2nd_plural": "rexeritis",
                "3rd_plural": "rexerint",
            },
            "konsonantische Konjugation-present-passive": {
                "1st_singular": "regor",
                "2nd_singular": "regeris",
                "3rd_singular": "regitur",
                "1st_plural": "regimur",
                "2nd_plural": "regimini",
                "3rd_plural": "reguntur",
            },
            "konsonantische Konjugation-past-passive": {
                "1st_singular": "rectus sum",
                "2nd_singular": "rectus es",
                "3rd_singular": "rectus est",
                "1st_plural": "recti sumus",
                "2nd_plural": "recti estis",
                "3rd_plural": "recti sunt",
            },
            "konsonantische Konjugation-perfect-passive": {
                "1st_singular": "rectus eram",
                "2nd_singular": "rectus eras",
                "3rd_singular": "rectus erat",
                "1st_plural": "recti eramus",
                "2nd_plural": "recti eratis",
                "3rd_plural": "recti erant",
            },
            "konsonantische Konjugation-pluperfect-passive": {
                "1st_singular": "rectus ero",
                "2nd_singular": "rectus eris",
                "3rd_singular": "rectus erit",
                "1st_plural": "recti erimus",
                "2nd_plural": "recti eritis",
                "3rd_plural": "recti erunt",
            },
            "gemischte Konjugation-present": {
                "1st_singular": "capio",
                "2nd_singular": "capis",
                "3rd_singular": "capit",
                "1st_plural": "capimus",
                "2nd_plural": "capitis",
                "3rd_plural": "capiunt",
            },
            "gemischte Konjugation-past": {
                "1st_singular": "cepi",
                "2nd_singular": "cepisti",
                "3rd_singular": "cepit",
                "1st_plural": "cepimus",
                "2nd_plural": "cepistis",
                "3rd_plural": "ceperunt",
            },
            "gemischte Konjugation-perfect": {
                "1st_singular": "ceperam",
                "2nd_singular": "ceperas",
                "3rd_singular": "ceperat",
                "1st_plural": "ceperamus",
                "2nd_plural": "ceperatis",
                "3rd_plural": "ceperant",
            },
            "gemischte Konjugation-pluperfect": {
                "1st_singular": "cepero",
                "2nd_singular": "ceperis",
                "3rd_singular": "ceperit",
                "1st_plural": "ceperimus",
                "2nd_plural": "ceperitis",
                "3rd_plural": "ceperint",
            },
            "gemischte Konjugation-present-passive": {
                "1st_singular": "capior",
                "2nd_singular": "caperis",
                "3rd_singular": "capitur",
                "1st_plural": "capimur",
                "2nd_plural": "capimini",
                "3rd_plural": "capiuntur",
            },
            "gemischte Konjugation-past-passive": {
                "1st_singular": "captus sum",
                "2nd_singular": "captus es",
                "3rd_singular": "captus est",
                "1st_plural": "capti sumus",
                "2nd_plural": "capti estis",
                "3rd_plural": "capti sunt",
            },
            "gemischte Konjugation-perfect-passive": {
                "1st_singular": "captus eram",
                "2nd_singular": "captus eras",
                "3rd_singular": "captus erat",
                "1st_plural": "capti eramus",
                "2nd_plural": "capti eratis",
                "3rd_plural": "capti erant",
            },
            "gemischte Konjugation-pluperfect-passive": {
                "1st_singular": "captus ero",
                "2nd_singular": "captus eris",
                "3rd_singular": "captus erit",
                "1st_plural": "capti erimus",
                "2nd_plural": "capti eritis",
                "3rd_plural": "capti erunt",
            },
        }