class Data:
    def __init__( self ):
        
        self.deklinationen = {
            "A-Deklination": {
                "nominativ_singular": "puella",
                "genitiv_singular": "puellae",
                "dativ_singular": "puellae",
                "akkusativ_singular": "puellam",
                "ablativ_singular": "puella",
                "nominativ_plural": "puellae",
                "genitiv_plural": "puellarum",
                "dativ_plural": "puellis",
                "akkusativ_plural": "puellas",
                "ablativ_plural": "puellis",
            },
    
            "O-Deklination": {
                "nominativ_singular": "dominus",
                "genitiv_singular": "domini",
                "dativ_singular": "domino",
                "akkusativ_singular": "dominum",
                "ablativ_singular": "domino",
                "nominativ_plural": "domini",
                "genitiv_plural": "dominorum",
                "dativ_plural": "dominis",
                "akkusativ_plural": "dominos",
                "ablativ_plural": "dominis",
            },
    
            "O-Deklination Neutrum": {
                "nominativ_singular": "bellum",
                "genitiv_singular": "belli",
                "dativ_singular": "bello",
                "akkusativ_singular": "bellum",
                "ablativ_singular": "bello",
                "nominativ_plural": "bella",
                "genitiv_plural": "bellorum",
                "dativ_plural": "bellis",
                "akkusativ_plural": "bella",
                "ablativ_plural": "bellis",
            },
    
            "konsonantische Deklination": {
                "nominativ_singular": "rex",
                "genitiv_singular": "regis",
                "dativ_singular": "regi",
                "akkusativ_singular": "regem",
                "ablativ_singular": "rege",
                "nominativ_plural": "reges",
                "genitiv_plural": "regum",
                "dativ_plural": "regibus",
                "akkusativ_plural": "reges",
                "ablativ_plural": "regibus",
            },
    
            "konsonantische Deklination neutrum": {
                "nominativ_singular": "corpus",
                "genitiv_singular": "corporis",
                "dativ_singular": "corpori",
                "akkusativ_singular": "corpus",
                "ablativ_singular": "corpore",
                "nominativ_plural": "corpora",
                "genitiv_plural": "corporum",
                "dativ_plural": "corporibus",
                "akkusativ_plural": "corpora",
                "ablativ_plural": "corporibus",
            },
            "konsonantische Deklination neutrum\n mit Gen. Plural -ium": {
                "nominativ_singular": "animal",
                "genitiv_singular": "animalis",
                "dativ_singular": "animali",
                "akkusativ_singular": "animal",
                "ablativ_singular": "animali",
                "nominativ_plural": "animalia",
                "genitiv_plural": "animalium",
                "dativ_plural": "animalibus",
                "akkusativ_plural": "animalia",
                "ablativ_plural": "animalibus",
            },
    
            "I-Deklination": {
                "nominativ_singular": "civis",
                "genitiv_singular": "civis",
                "dativ_singular": "civi",
                "akkusativ_singular": "civem",
                "ablativ_singular": "cive",
                "nominativ_plural": "cives",
                "genitiv_plural": "civium",
                "dativ_plural": "civibus",
                "akkusativ_plural": "cives",
                "ablativ_plural": "civibus",
            },
    
            "I-Deklination Neutrum": {
                "nominativ_singular": "mare",
                "genitiv_singular": "maris",
                "dativ_singular": "mari",
                "akkusativ_singular": "mare",
                "ablativ_singular": "mari",
                "nominativ_plural": "maria",
                "genitiv_plural": "marium",
                "dativ_plural": "maribus",
                "akkusativ_plural": "maria",
                "ablativ_plural": "maribus",
            },
    
            "U-Deklination": {
                "nominativ_singular": "manus",
                "genitiv_singular": "manus",
                "dativ_singular": "manui",
                "akkusativ_singular": "manum",
                "ablativ_singular": "manu",
                "nominativ_plural": "manus",
                "genitiv_plural": "manuum",
                "dativ_plural": "manibus",
                "akkusativ_plural": "manus",
                "ablativ_plural": "manibus",
            },
    
            "E-Deklination": {
                "nominativ_singular": "res",
                "genitiv_singular": "rei",
                "dativ_singular": "rei",
                "akkusativ_singular": "rem",
                "ablativ_singular": "re",
                "nominativ_plural": "res",
                "genitiv_plural": "rerum",
                "dativ_plural": "rebus",
                "akkusativ_plural": "res",
                "ablativ_plural": "rebus",
            },
        }

        self.konjugationen = {
            "a-Konjugation Präsens": {
                "1._Person_Singular": "amo",
                "2._Person_Singular": "amas",
                "3._Person_Singular": "amat",
                "1._Person_Plural": "amamus",
                "2._Person_Plural": "amatis",
                "3._Person_Plural": "amant",
            },
            "a-Konjugation Imperfekt": {
                "1._Person_Singular": "amabam",
                "2._Person_Singular": "amabas",
                "3._Person_Singular": "amabat",
                "1._Person_Plural": "amabamus",
                "2._Person_Plural": "amabatis",
                "3._Person_Plural": "amabant",
            },
            "a-Konjugation Plusquamperfekt": {
                "1._Person_Singular": "amaveram",
                "2._Person_Singular": "amaveras",
                "3._Person_Singular": "amaverat",
                "1._Person_Plural": "amaveramus",
                "2._Person_Plural": "amaveratis",
                "3._Person_Plural": "amaverant",
            },
            "a-Konjugation Perfekt": {
                "1._Person_Singular": "amavi",
                "2._Person_Singular": "amavisti",
                "3._Person_Singular": "amavit",
                "1._Person_Plural": "amavimus",
                "2._Person_Plural": "amavistis",
                "3._Person_Plural": "amaverunt",
            },
            "a-Konjugation Futur 1": {
                "1._Person_Singular": "amabo",
                "2._Person_Singular": "amabis",
                "3._Person_Singular": "amabit",
                "1._Person_Plural": "amabimus",
                "2._Person_Plural": "amabitis",
                "3._Person_Plural": "amabunt",
            },
            "a-Konjugation PPA": {
                "Singular": "amans",
                "Plural": "amantes",
            },
            "a-Konjugation PPP": {
                "Singular": "amatus",
                "Plural": "amati",
            },
            "a-Konjugation PFA": {
                "Singular": "amaturus",
                "Plural": "amaturi",
            },
            "e-Konjugation Präsens": {
                "1._Person_Singular": "moneo",
                "2._Person_Singular": "mones",
                "3._Person_Singular": "monet",
                "1._Person_Plural": "monemus",
                "2._Person_Plural": "monetis",
                "3._Person_Plural": "monent",
            },
            "e-Konjugation Imperfekt": {
                "1._Person_Singular": "monebam",
                "2._Person_Singular": "monebas",
                "3._Person_Singular": "monebat",
                "1._Person_Plural": "monebamus",
                "2._Person_Plural": "monebatis",
                "3._Person_Plural": "monebant",
            },
            "e-Konjugation Plusquamperfekt": {
                "1._Person_Singular": "monueram",
                "2._Person_Singular": "monueras",
                "3._Person_Singular": "monuerat",
                "1._Person_Plural": "monueramus",
                "2._Person_Plural": "monueratis",
                "3._Person_Plural": "monuerant",
            },
            "e-Konjugation Perfekt": {
                "1._Person_Singular": "monui",
                "2._Person_Singular": "monuisti",
                "3._Person_Singular": "monuit",
                "1._Person_Plural": "monuimus",
                "2._Person_Plural": "monuistis",
                "3._Person_Plural": "monuerunt",
            },
            "e-Konjugation Futur 1": {
                "1._Person_Singular": "monebo",
                "2._Person_Singular": "monebis",
                "3._Person_Singular": "monebit",
                "1._Person_Plural": "monebimus",
                "2._Person_Plural": "monebitis",
                "3._Person_Plural": "monebunt",
            },
            "e-Konjugation PPA": {
                "Singular": "monens",
                "Plural": "monentes",
            },
            "e-Konjugation PPP": {
                "Singular": "monitus",
                "Plural": "moniti",
            },
            "e-Konjugation PFA": {
                "Singular": "moniturus",
                "Plural": "monituri",
            },
            "i-Konjugation Präsens": {
                "1._Person_Singular": "audio",
                "2._Person_Singular": "audis",
                "3._Person_Singular": "audit",
                "1._Person_Plural": "audimus",
                "2._Person_Plural": "auditis",
                "3._Person_Plural": "audiunt",
            },
            "i-Konjugation Imperfekt": {
                "1._Person_Singular": "audiebam",
                "2._Person_Singular": "audiebas",
                "3._Person_Singular": "audiebat",
                "1._Person_Plural": "audiebamus",
                "2._Person_Plural": "audiebatis",
                "3._Person_Plural": "audiebant",
            },
            "i-Konjugation Plusquamperfekt": {
                "1._Person_Singular": "audiveram",
                "2._Person_Singular": "audiveras",
                "3._Person_Singular": "audiverat",
                "1._Person_Plural": "audiveramus",
                "2._Person_Plural": "audiveratis",
                "3._Person_Plural": "audiverant",
            },
            "i-Konjugation Perfekt": {
                "1._Person_Singular": "audivi",
                "2._Person_Singular": "audivisti",
                "3._Person_Singular": "audivit",
                "1._Person_Plural": "audivimus",
                "2._Person_Plural": "audivistis",
                "3._Person_Plural": "audiverunt",
            },
            "i-Konjugation Futur 1": {
                "1._Person_Singular": "audiam",
                "2._Person_Singular": "audies",
                "3._Person_Singular": "audiet",
                "1._Person_Plural": "audiemus",
                "2._Person_Plural": "audietis",
                "3._Person_Plural": "audient",
            },
            "i-Konjugation PPA": {
                "Singular": "audiens",
                "Plural": "audientes",
            },
            "i-Konjugation PPP": {
                "Singular": "auditus",
                "Plural": "auditi",
            },
            "i-Konjugation PFA": {
                "Singular": "auditurus",
                "Plural": "audituri",
            },
            "konsonantische Konjugation Präsens": {
                "1._Person_Singular": "rego",
                "2._Person_Singular": "regis",
                "3._Person_Singular": "regit",
                "1._Person_Plural": "regimus",
                "2._Person_Plural": "regitis",
                "3._Person_Plural": "regunt",
            },
            "konsonantische Konjugation Imperfekt": {
                "1._Person_Singular": "regebam",
                "2._Person_Singular": "regebas",
                "3._Person_Singular": "regebat",
                "1._Person_Plural": "regebamus",
                "2._Person_Plural": "regebatis",
                "3._Person_Plural": "regebant",
            },
            "konsonantische Konjugation Plusquamperfekt": {
                "1._Person_Singular": "rexeram",
                "2._Person_Singular": "rexeras",
                "3._Person_Singular": "rexerat",
                "1._Person_Plural": "rexeramus",
                "2._Person_Plural": "rexeratis",
                "3._Person_Plural": "rexerant",
            },
            "konsonantische Konjugation Perfekt": {
                "1._Person_Singular": "rexi",
                "2._Person_Singular": "rexisti",
                "3._Person_Singular": "rexit",
                "1._Person_Plural": "reximus",
                "2._Person_Plural": "rexistis",
                "3._Person_Plural": "rexerunt",
            },
            "konsonantische Konjugation Futur 1": {
                "1._Person_Singular": "regam",
                "2._Person_Singular": "reges",
                "3._Person_Singular": "reget",
                "1._Person_Plural": "regemus",
                "2._Person_Plural": "regetis",
                "3._Person_Plural": "regent",
            },
            "konsonantische Konjugation PPA": {
                "Singular": "regens",
                "Plural": "regentes",
            },
            "konsonantische Konjugation PPP": {
                "Singular": "rectus",
                "Plural": "recti",
            },
            "konsonantische Konjugation PFA": {
                "Singular": "recturus",
                "Plural": "recturi",
            },
            "gemischte Konjugation Präsens": {
                "1._Person_Singular": "capio",
                "2._Person_Singular": "capis",
                "3._Person_Singular": "capit",
                "1._Person_Plural": "capimus",
                "2._Person_Plural": "capitis",
                "3._Person_Plural": "capiunt",
            },
            "gemischte Konjugation Imperfekt": {
                "1._Person_Singular": "capiebam",
                "2._Person_Singular": "capiebas",
                "3._Person_Singular": "capiebat",
                "1._Person_Plural": "capiebamus",
                "2._Person_Plural": "capiebatis",
                "3._Person_Plural": "capiebant",
            },
            "gemischte Konjugation Plusquamperfekt": {
                "1._Person_Singular": "ceperam",
                "2._Person_Singular": "ceperas",
                "3._Person_Singular": "ceperat",
                "1._Person_Plural": "ceperamus",
                "2._Person_Plural": "ceperatis",
                "3._Person_Plural": "ceperant",
            },
            "gemischte Konjugation Perfekt": {
                "1._Person_Singular": "cepi",
                "2._Person_Singular": "cepisti",
                "3._Person_Singular": "cepit",
                "1._Person_Plural": "cepimus",
                "2._Person_Plural": "cepistis",
                "3._Person_Plural": "ceperunt",
            },
            "gemischte Konjugation Futur 1": {
                "1._Person_Singular": "capiam",
                "2._Person_Singular": "capies",
                "3._Person_Singular": "capiet",
                "1._Person_Plural": "capiemus",
                "2._Person_Plural": "capietis",
                "3._Person_Plural": "capient",
            },
            "gemischte Konjugation PPA": {
                "Singular": "capiens",
                "Plural": "capientes",
            },
            "gemischte Konjugation PPP": {
                "Singular": "captus",
                "Plural": "capti",
            },
            "gemischte Konjugation PFA": {
                "Singular": "capturus",
                "Plural": "capturi",
            }
        }