class Data:
    def __init__( self ):
        
        self.deklinationen = {
            "A-Deklination": {
                "nominativ_Singular": "puella",
                "genitiv_Singular": "puellae",
                "dativ_Singular": "puellae",
                "akkusativ_Singular": "puellam",
                "ablativ_Singular": "puella",
                "nominativ_Pluar": "puellae",
                "genitiv_Pluar": "puellarum",
                "dativ_Pluar": "puellis",
                "akkusativ_Pluar": "puellas",
                "ablativ_Pluar": "puellis",
            },
    
            "O-Deklination": {
                "nominativ_Singular": "dominus",
                "genitiv_Singular": "domini",
                "dativ_Singular": "domino",
                "akkusativ_Singular": "dominum",
                "ablativ_Singular": "domino",
                "nominativ_Pluar": "domini",
                "genitiv_Pluar": "dominorum",
                "dativ_Pluar": "dominis",
                "akkusativ_Pluar": "dominos",
                "ablativ_Pluar": "dominis",
            },
    
            "O-Deklination Neutrum": {
                "nominativ_Singular": "bellum",
                "genitiv_Singular": "belli",
                "dativ_Singular": "bello",
                "akkusativ_Singular": "bellum",
                "ablativ_Singular": "bello",
                "nominativ_Pluar": "bella",
                "genitiv_Pluar": "bellorum",
                "dativ_Pluar": "bellis",
                "akkusativ_Pluar": "bella",
                "ablativ_Pluar": "bellis",
            },
    
            "konsonantische Deklination": {
                "nominativ_Singular": "rex",
                "genitiv_Singular": "regis",
                "dativ_Singular": "regi",
                "akkusativ_Singular": "regem",
                "ablativ_Singular": "rege",
                "nominativ_Pluar": "reges",
                "genitiv_Pluar": "regum",
                "dativ_Pluar": "regibus",
                "akkusativ_Pluar": "reges",
                "ablativ_Pluar": "regibus",
            },
    
            "konsonantische Deklination\nneutrum": {
                "nominativ_Singular": "corpus",
                "genitiv_Singular": "corporis",
                "dativ_Singular": "corpori",
                "akkusativ_Singular": "corpus",
                "ablativ_Singular": "corpore",
                "nominativ_Pluar": "corpora",
                "genitiv_Pluar": "corporum",
                "dativ_Pluar": "corporibus",
                "akkusativ_Pluar": "corpora",
                "ablativ_Pluar": "corporibus",
            },
            "konsonantische Deklination neutrum\n mit Gen. Plural -ium": {
                "nominativ_Singular": "animal",
                "genitiv_Singular": "animalis",
                "dativ_Singular": "animali",
                "akkusativ_Singular": "animal",
                "ablativ_Singular": "animali",
                "nominativ_Pluar": "animalia",
                "genitiv_Pluar": "animalium",
                "dativ_Pluar": "animalibus",
                "akkusativ_Pluar": "animalia",
                "ablativ_Pluar": "animalibus",
            },
    
            "I-Deklination": {
                "nominativ_Singular": "civis",
                "genitiv_Singular": "civis",
                "dativ_Singular": "civi",
                "akkusativ_Singular": "civem",
                "ablativ_Singular": "cive",
                "nominativ_Pluar": "cives",
                "genitiv_Pluar": "civium",
                "dativ_Pluar": "civibus",
                "akkusativ_Pluar": "cives",
                "ablativ_Pluar": "civibus",
            },
    
            "I-Deklination Neutrum": {
                "nominativ_Singular": "mare",
                "genitiv_Singular": "maris",
                "dativ_Singular": "mari",
                "akkusativ_Singular": "mare",
                "ablativ_Singular": "mari",
                "nominativ_Pluar": "maria",
                "genitiv_Pluar": "marium",
                "dativ_Pluar": "maribus",
                "akkusativ_Pluar": "maria",
                "ablativ_Pluar": "maribus",
            },
    
            "U-Deklination": {
                "nominativ_Singular": "manus",
                "genitiv_Singular": "manus",
                "dativ_Singular": "manui",
                "akkusativ_Singular": "manum",
                "ablativ_Singular": "manu",
                "nominativ_Pluar": "manus",
                "genitiv_Pluar": "manuum",
                "dativ_Pluar": "manibus",
                "akkusativ_Pluar": "manus",
                "ablativ_Pluar": "manibus",
            },
    
            "E-Deklination": {
                "nominativ_Singular": "res",
                "genitiv_Singular": "rei",
                "dativ_Singular": "rei",
                "akkusativ_Singular": "rem",
                "ablativ_Singular": "re",
                "nominativ_Pluar": "res",
                "genitiv_Pluar": "rerum",
                "dativ_Pluar": "rebus",
                "akkusativ_Pluar": "res",
                "ablativ_Pluar": "rebus",
            },
        }

        self.konjugationen = {
            "a-Konjugation Präsens": {
                "1._Person_Singular": "amo",
                "2._Person_Singular": "amas",
                "3._Person_Singular": "amat",
                "1._Person_Plural": "amamus",
                "2._Person_Plural": "amatis",
                "3._Person_Plural": "amant",
            },
            "a-Konjugation Imperfekt": {
                "1._Person_Singular": "amabam",
                "2._Person_Singular": "amabas",
                "3._Person_Singular": "amabat",
                "1._Person_Plural": "amabamus",
                "2._Person_Plural": "amabatis",
                "3._Person_Plural": "amabant",
            },
            "a-Konjugation Plusquamperfekt": {
                "1._Person_Singular": "amaveram",
                "2._Person_Singular": "amaveras",
                "3._Person_Singular": "amaverat",
                "1._Person_Plural": "amaveramus",
                "2._Person_Plural": "amaveratis",
                "3._Person_Plural": "amaverant",
            },
            "a-Konjugation Perfekt": {
                "1._Person_Singular": "amavi",
                "2._Person_Singular": "amavisti",
                "3._Person_Singular": "amavit",
                "1._Person_Plural": "amavimus",
                "2._Person_Plural": "amavistis",
                "3._Person_Plural": "amaverunt",
            },
            "a-Konjugation Futur 1": {
                "1._Person_Singular": "amabo",
                "2._Person_Singular": "amabis",
                "3._Person_Singular": "amabit",
                "1._Person_Plural": "amabimus",
                "2._Person_Plural": "amabitis",
                "3._Person_Plural": "amabunt",
            },
            "a-Konjugation Futur 2": {
                "1._Person_Singular": "amavero",
                "2._Person_Singular": "amaveris",
                "3._Person_Singular": "amaverit",
                "1._Person_Plural": "amaverimus",
                "2._Person_Plural": "amaveritis",
                "3._Person_Plural": "amaverint",
            },
            "a-Konjugation PPA": {
                "Singular": "amans",
                "Plural": "amantes",
            },
            "a-Konjugation PPP": {
                "Singular": "amatus",
                "Plural": "amati",
            },
            "a-Konjugation PFA": {
                "Singular": "amaturus",
                "Plural": "amaturi",
            },
            "a-Konjugation Passiv Präsens": {
                "1._Person_Singular": "amor",
                "2._Person_Singular": "amaris",
                "3._Person_Singular": "amatur",
                "1._Person_Plural": "amamur",
                "2._Person_Plural": "amamini",
                "3._Person_Plural": "amantur",
            },
            "a-Konjugation Passiv Imperfekt": {
                "1._Person_Singular": "amabar",
                "2._Person_Singular": "amabaris",
                "3._Person_Singular": "amabatur",
                "1._Person_Plural": "amabamur",
                "2._Person_Plural": "amabamini",
                "3._Person_Plural": "amabantur",
            },
            "a-Konjugation Passiv Perfekt": {
                "1._Person_Singular": "amatus sum",
                "2._Person_Singular": "amatus es",
                "3._Person_Singular": "amatus est",
                "1._Person_Plural": "amati sumus",
                "2._Person_Plural": "amati estis",
                "3._Person_Plural": "amati sunt",
            },
            "a-Konjugation Passiv Plusquamperfekt": {
                "1._Person_Singular": "amatus eram",
                "2._Person_Singular": "amatus eras",
                "3._Person_Singular": "amatus erat",
                "1._Person_Plural": "amati eramus",
                "2._Person_Plural": "amati eratis",
                "3._Person_Plural": "amati erant",
            },
            "a-Konjugation Passiv Futur 1": {
                "1._Person_Singular": "amabor",
                "2._Person_Singular": "amaberis",
                "3._Person_Singular": "amabitur",
                "1._Person_Plural": "amabimur",
                "2._Person_Plural": "amabimini",
                "3._Person_Plural": "amabuntur",
            },
            "a-Konjugation Passiv Futur 2": {
                "1._Person_Singular": "amatus ero",
                "2._Person_Singular": "amatus eris",
                "3._Person_Singular": "amatus erit",
                "1._Person_Plural": "amati erimus",
                "2._Person_Plural": "amati eritis",
                "3._Person_Plural": "amati erunt",
            },
            "a-Konjugation Konjunktiv Präsens": {
                "1._Person_Singular": "amem",
                "2._Person_Singular": "ames",
                "3._Person_Singular": "amet",
                "1._Person_Plural": "amemus",
                "2._Person_Plural": "ametis",
                "3._Person_Plural": "ament",
            },
            "a-Konjugation Konjunktiv Imperfekt": {
                "1._Person_Singular": "amarem",
                "2._Person_Singular": "amares",
                "3._Person_Singular": "amaret",
                "1._Person_Plural": "amaremus",
                "2._Person_Plural": "amaretis",
                "3._Person_Plural": "amarent",
            },
            "a-Konjugation Konjunktiv Perfekt": {
                "1._Person_Singular": "amaverim",
                "2._Person_Singular": "amaveris",
                "3._Person_Singular": "amaverit",
                "1._Person_Plural": "amaverimus",
                "2._Person_Plural": "amaveritis",
                "3._Person_Plural": "amaverint",
            },
            "a-Konjugation Konjunktiv Plusquamperfekt": {
                "1._Person_Singular": "amavissem",
                "2._Person_Singular": "amavisses",
                "3._Person_Singular": "amavisset",
                "1._Person_Plural": "amavissemus",
                "2._Person_Plural": "amavissetis",
                "3._Person_Plural": "amavissent",
            },
            "a-Konjugation Passiv Konjunktiv Präsens": {
                "1._Person_Singular": "amer",
                "2._Person_Singular": "ameris",
                "3._Person_Singular": "ametur",
                "1._Person_Plural": "amemur",
                "2._Person_Plural": "amemini",
                "3._Person_Plural": "amentur",
            },
            "a-Konjugation Passiv Konjunktiv Imperfekt": {
                "1._Person_Singular": "amarer",
                "2._Person_Singular": "amareris",
                "3._Person_Singular": "amaretur",
                "1._Person_Plural": "amaremur",
                "2._Person_Plural": "amaremini",
                "3._Person_Plural": "amarentur",
            },
            "a-Konjugation Passiv Konjunktiv Perfekt": {
                "1._Person_Singular": "amatus sim",
                "2._Person_Singular": "amatus sis",
                "3._Person_Singular": "amatus sit",
                "1._Person_Plural": "amati simus",
                "2._Person_Plural": "amati sitis",
                "3._Person_Plural": "amati sint",
            },
            "a-Konjugation Passiv Konjunktiv Plusquamperfekt": {
                "1._Person_Singular": "amatus essem",
                "2._Person_Singular": "amatus esses",
                "3._Person_Singular": "amatus esset",
                "1._Person_Plural": "amati essemus",
                "2._Person_Plural": "amati essetis",
                "3._Person_Plural": "amati essent",
            },
            "e-Konjugation Präsens": {
                "1._Person_Singular": "moneo",
                "2._Person_Singular": "mones",
                "3._Person_Singular": "monet",
                "1._Person_Plural": "monemus",
                "2._Person_Plural": "monetis",
                "3._Person_Plural": "monent",
            },
            "e-Konjugation Imperfekt": {
                "1._Person_Singular": "monebam",
                "2._Person_Singular": "monebas",
                "3._Person_Singular": "monebat",
                "1._Person_Plural": "monebamus",
                "2._Person_Plural": "monebatis",
                "3._Person_Plural": "monebant",
            },
            "e-Konjugation Plusquamperfekt": {
                "1._Person_Singular": "monueram",
                "2._Person_Singular": "monueras",
                "3._Person_Singular": "monuerat",
                "1._Person_Plural": "monueramus",
                "2._Person_Plural": "monueratis",
                "3._Person_Plural": "monuerant",
            },
            "e-Konjugation Perfekt": {
                "1._Person_Singular": "monui",
                "2._Person_Singular": "monuisti",
                "3._Person_Singular": "monuit",
                "1._Person_Plural": "monuimus",
                "2._Person_Plural": "monuistis",
                "3._Person_Plural": "monuerunt",
            },
            "e-Konjugation Futur 1": {
                "1._Person_Singular": "monebo",
                "2._Person_Singular": "monebis",
                "3._Person_Singular": "monebit",
                "1._Person_Plural": "monebimus",
                "2._Person_Plural": "monebitis",
                "3._Person_Plural": "monebunt",
            },
            "e-Konjugation Futur 2": {
                "1._Person_Singular": "monuero",
                "2._Person_Singular": "monueris",
                "3._Person_Singular": "monuerit",
                "1._Person_Plural": "monuerimus",
                "2._Person_Plural": "monueritis",
                "3._Person_Plural": "monuerint",
            },
            "e-Konjugation PPA": {
                "Singular": "monens",
                "Plural": "monentes",
            },
            "e-Konjugation PPP": {
                "Singular": "monitus",
                "Plural": "moniti",
            },
            "e-Konjugation PFA": {
                "Singular": "moniturus",
                "Plural": "monituri",
            },
            "e-Konjugation Passiv Präsens": {
                "1._Person_Singular": "moneor",
                "2._Person_Singular": "moneris",
                "3._Person_Singular": "monetur",
                "1._Person_Plural": "monemur",
                "2._Person_Plural": "monemini",
                "3._Person_Plural": "monentur",
            },
            "e-Konjugation Passiv Imperfekt": {
                "1._Person_Singular": "monebar",
                "2._Person_Singular": "monebaris",
                "3._Person_Singular": "monebatur",
                "1._Person_Plural": "monebamur",
                "2._Person_Plural": "monebamini",
                "3._Person_Plural": "monebantur",
            },
            "e-Konjugation Passiv Perfekt": {
                "1._Person_Singular": "monitus sum",
                "2._Person_Singular": "monitus es",
                "3._Person_Singular": "monitus est",
                "1._Person_Plural": "moniti sumus",
                "2._Person_Plural": "moniti estis",
                "3._Person_Plural": "moniti sunt",
            },
            "e-Konjugation Passiv Plusquamperfekt": {
                "1._Person_Singular": "monitus eram",
                "2._Person_Singular": "monitus eras",
                "3._Person_Singular": "monitus erat",
                "1._Person_Plural": "moniti eramus",
                "2._Person_Plural": "moniti eratis",
                "3._Person_Plural": "moniti erant",
            },
            "e-Konjugation Passiv Futur 1": {
                "1._Person_Singular": "monebor",
                "2._Person_Singular": "moneberis",
                "3._Person_Singular": "monebitur",
                "1._Person_Plural": "monebimur",
                "2._Person_Plural": "monebimini",
                "3._Person_Plural": "monebuntur",
            },
            "e-Konjugation Passiv Futur 2": {
                "1._Person_Singular": "monitus ero",
                "2._Person_Singular": "monitus eris",
                "3._Person_Singular": "monitus erit",
                "1._Person_Plural": "moniti erimus",
                "2._Person_Plural": "moniti eritis",
                "3._Person_Plural": "moniti erunt",
            },
            "e-Konjugation Konjunktiv Präsens": {
                "1._Person_Singular": "moneam",
                "2._Person_Singular": "moneas",
                "3._Person_Singular": "moneat",
                "1._Person_Plural": "moneamus",
                "2._Person_Plural": "moneatis",
                "3._Person_Plural": "moneant",
            },
            "e-Konjugation Konjunktiv Imperfekt": {
                "1._Person_Singular": "monerem",
                "2._Person_Singular": "moneres",
                "3._Person_Singular": "moneret",
                "1._Person_Plural": "moneremus",
                "2._Person_Plural": "moneretis",
                "3._Person_Plural": "monerent",
            },
            "e-Konjugation Konjunktiv Perfekt": {
                "1._Person_Singular": "monuerim",
                "2._Person_Singular": "monueris",
                "3._Person_Singular": "monuerit",
                "1._Person_Plural": "monuerimus",
                "2._Person_Plural": "monueritis",
                "3._Person_Plural": "monuerint",
            },
            "e-Konjugation Konjunktiv Plusquamperfekt": {
                "1._Person_Singular": "monuissem",
                "2._Person_Singular": "monuisses",
                "3._Person_Singular": "monuisset",
                "1._Person_Plural": "monuissemus",
                "2._Person_Plural": "monuissetis",
                "3._Person_Plural": "monuissent",
            },
            "e-Konjugation Passiv Konjunktiv Präsens": {
                "1._Person_Singular": "monear",
                "2._Person_Singular": "monearis",
                "3._Person_Singular": "moneatur",
                "1._Person_Plural": "moneamur",
                "2._Person_Plural": "moneamini",
                "3._Person_Plural": "moneantur",
            },
            "e-Konjugation Passiv Konjunktiv Imperfekt": {
                "1._Person_Singular": "monerer",
                "2._Person_Singular": "monereris",
                "3._Person_Singular": "moneretur",
                "1._Person_Plural": "moneremur",
                "2._Person_Plural": "moneremini",
                "3._Person_Plural": "monerentur",
            },
            "e-Konjugation Passiv Konjunktiv Perfekt": {
                "1._Person_Singular": "monitus sim",
                "2._Person_Singular": "monitus sis",
                "3._Person_Singular": "monitus sit",
                "1._Person_Plural": "moniti simus",
                "2._Person_Plural": "moniti sitis",
                "3._Person_Plural": "moniti sint",
            },
            "e-Konjugation Passiv Konjunktiv Plusquamperfekt": {
                "1._Person_Singular": "monitus essem",
                "2._Person_Singular": "monitus esses",
                "3._Person_Singular": "monitus esset",
                "1._Person_Plural": "moniti essemus",
                "2._Person_Plural": "moniti essetis",
                "3._Person_Plural": "moniti essent",
            },
            "i-Konjugation Präsens": {
                "1._Person_Singular": "audio",
                "2._Person_Singular": "audis",
                "3._Person_Singular": "audit",
                "1._Person_Plural": "audimus",
                "2._Person_Plural": "auditis",
                "3._Person_Plural": "audiunt",
            },
            "i-Konjugation Imperfekt": {
                "1._Person_Singular": "audiebam",
                "2._Person_Singular": "audiebas",
                "3._Person_Singular": "audiebat",
                "1._Person_Plural": "audiebamus",
                "2._Person_Plural": "audiebatis",
                "3._Person_Plural": "audiebant",
            },
            "i-Konjugation Plusquamperfekt": {
                "1._Person_Singular": "audiveram",
                "2._Person_Singular": "audiveras",
                "3._Person_Singular": "audiverat",
                "1._Person_Plural": "audiveramus",
                "2._Person_Plural": "audiveratis",
                "3._Person_Plural": "audiverant",
            },
            "i-Konjugation Perfekt": {
                "1._Person_Singular": "audivi",
                "2._Person_Singular": "audivisti",
                "3._Person_Singular": "audivit",
                "1._Person_Plural": "audivimus",
                "2._Person_Plural": "audivistis",
                "3._Person_Plural": "audiverunt",
            },
            "i-Konjugation Futur 1": {
                "1._Person_Singular": "audiam",
                "2._Person_Singular": "audies",
                "3._Person_Singular": "audiet",
                "1._Person_Plural": "audiemus",
                "2._Person_Plural": "audietis",
                "3._Person_Plural": "audient",
            },
            "i-Konjugation Futur 2": {
                "1._Person_Singular": "audivero",
                "2._Person_Singular": "audiveris",
                "3._Person_Singular": "audiverit",
                "1._Person_Plural": "audiverimus",
                "2._Person_Plural": "audiveritis",
                "3._Person_Plural": "audiverint",
            },
            "i-Konjugation PPA": {
                "Singular": "audiens",
                "Plural": "audientes",
            },
            "i-Konjugation PPP": {
                "Singular": "auditus",
                "Plural": "auditi",
            },
            "i-Konjugation PFA": {
                "Singular": "auditurus",
                "Plural": "audituri",
            },
            "i-Konjugation Passiv Präsens": {
                "1._Person_Singular": "audior",
                "2._Person_Singular": "audiris",
                "3._Person_Singular": "auditur",
                "1._Person_Plural": "audimur",
                "2._Person_Plural": "audimini",
                "3._Person_Plural": "audiuntur",
            },
            "i-Konjugation Passiv Imperfekt": {
                "1._Person_Singular": "audiebar",
                "2._Person_Singular": "audiebaris",
                "3._Person_Singular": "audiebatur",
                "1._Person_Plural": "audiebamur",
                "2._Person_Plural": "audiebamini",
                "3._Person_Plural": "audiebantur",
            },
            "i-Konjugation Passiv Perfekt": {
                "1._Person_Singular": "auditus sum",
                "2._Person_Singular": "auditus es",
                "3._Person_Singular": "auditus est",
                "1._Person_Plural": "auditi sumus",
                "2._Person_Plural": "auditi estis",
                "3._Person_Plural": "auditi sunt",
            },
            "i-Konjugation Passiv Plusquamperfekt": {
                "1._Person_Singular": "auditus eram",
                "2._Person_Singular": "auditus eras",
                "3._Person_Singular": "auditus erat",
                "1._Person_Plural": "auditi eramus",
                "2._Person_Plural": "auditi eratis",
                "3._Person_Plural": "auditi erant",
            },
            "i-Konjugation Passiv Futur 1": {
                "1._Person_Singular": "audiar",
                "2._Person_Singular": "audieris",
                "3._Person_Singular": "audietur",
                "1._Person_Plural": "audiemur",
                "2._Person_Plural": "audiemini",
                "3._Person_Plural": "audientur",
            },
            "i-Konjugation Passiv Futur 2": {
                "1._Person_Singular": "auditus ero",
                "2._Person_Singular": "auditus eris",
                "3._Person_Singular": "auditus erit",
                "1._Person_Plural": "auditi erimus",
                "2._Person_Plural": "auditi eritis",
                "3._Person_Plural": "auditi erunt",
            },
            "i-Konjugation Konjunktiv Präsens": {
                "1._Person_Singular": "audiam",
                "2._Person_Singular": "audias",
                "3._Person_Singular": "audiat",
                "1._Person_Plural": "audiamus",
                "2._Person_Plural": "audiatis",
                "3._Person_Plural": "audiant",
            },
            "i-Konjugation Konjunktiv Imperfekt": {
                "1._Person_Singular": "audirem",
                "2._Person_Singular": "audires",
                "3._Person_Singular": "audiret",
                "1._Person_Plural": "audiremus",
                "2._Person_Plural": "audiretis",
                "3._Person_Plural": "audirent",
            },
            "i-Konjugation Konjunktiv Perfekt": {
                "1._Person_Singular": "audiverim",
                "2._Person_Singular": "audiveris",
                "3._Person_Singular": "audiverit",
                "1._Person_Plural": "audiverimus",
                "2._Person_Plural": "audiveritis",
                "3._Person_Plural": "audiverint",
            },
            "i-Konjugation Konjunktiv Plusquamperfekt": {
                "1._Person_Singular": "audivissem",
                "2._Person_Singular": "audivisses",
                "3._Person_Singular": "audivisset",
                "1._Person_Plural": "audivissemus",
                "2._Person_Plural": "audivissetis",
                "3._Person_Plural": "audivissent",
            },"i-Konjugation Passiv Konjunktiv Präsens": {
                "1._Person_Singular": "audiar",
                "2._Person_Singular": "audiaris",
                "3._Person_Singular": "audiatur",
                "1._Person_Plural": "audiamur",
                "2._Person_Plural": "audiamini",
                "3._Person_Plural": "audiantur",
            },
            "i-Konjugation Passiv Konjunktiv Imperfekt": {
                "1._Person_Singular": "audirer",
                "2._Person_Singular": "audireris",
                "3._Person_Singular": "audiretur",
                "1._Person_Plural": "audiremur",
                "2._Person_Plural": "audiremini",
                "3._Person_Plural": "audirentur",
            },
            "i-Konjugation Passiv Konjunktiv Perfekt": {
                "1._Person_Singular": "auditus sim",
                "2._Person_Singular": "auditus sis",
                "3._Person_Singular": "auditus sit",
                "1._Person_Plural": "auditi simus",
                "2._Person_Plural": "auditi sitis",
                "3._Person_Plural": "auditi sint",
            },
            "i-Konjugation Passiv Konjunktiv Plusquamperfekt": {
                "1._Person_Singular": "auditus essem",
                "2._Person_Singular": "auditus esses",
                "3._Person_Singular": "auditus esset",
                "1._Person_Plural": "auditi essemus",
                "2._Person_Plural": "auditi essetis",
                "3._Person_Plural": "auditi essent",
            },
            "konsonantische Konjugation Präsens": {
                "1._Person_Singular": "rego",
                "2._Person_Singular": "regis",
                "3._Person_Singular": "regit",
                "1._Person_Plural": "regimus",
                "2._Person_Plural": "regitis",
                "3._Person_Plural": "regunt",
            },
            "konsonantische Konjugation Imperfekt": {
                "1._Person_Singular": "regebam",
                "2._Person_Singular": "regebas",
                "3._Person_Singular": "regebat",
                "1._Person_Plural": "regebamus",
                "2._Person_Plural": "regebatis",
                "3._Person_Plural": "regebant",
            },
            "konsonantische Konjugation Plusquamperfekt": {
                "1._Person_Singular": "rexeram",
                "2._Person_Singular": "rexeras",
                "3._Person_Singular": "rexerat",
                "1._Person_Plural": "rexeramus",
                "2._Person_Plural": "rexeratis",
                "3._Person_Plural": "rexerant",
            },
            "konsonantische Konjugation Perfekt": {
                "1._Person_Singular": "rexi",
                "2._Person_Singular": "rexisti",
                "3._Person_Singular": "rexit",
                "1._Person_Plural": "reximus",
                "2._Person_Plural": "rexistis",
                "3._Person_Plural": "rexerunt",
            },
            "konsonantische Konjugation Futur 1": {
                "1._Person_Singular": "regam",
                "2._Person_Singular": "reges",
                "3._Person_Singular": "reget",
                "1._Person_Plural": "regemus",
                "2._Person_Plural": "regetis",
                "3._Person_Plural": "regent",
            },
            "konsonantische Konjugation Futur 2": {
                "1._Person_Singular": "rexero",
                "2._Person_Singular": "rexeris",
                "3._Person_Singular": "rexerit",
                "1._Person_Plural": "rexerimus",
                "2._Person_Plural": "rexeritis",
                "3._Person_Plural": "rexerint",
            },
            "konsonantische Konjugation PPA": {
                "Singular": "regens",
                "Plural": "regentes",
            },
            "konsonantische Konjugation PPP": {
                "Singular": "rectus",
                "Plural": "recti",
            },
            "konsonantische Konjugation PFA": {
                "Singular": "recturus",
                "Plural": "recturi",
            },
            "konsonantische Konjugation Passiv Präsens": {
                "1._Person_Singular": "regor",
                "2._Person_Singular": "regeris",
                "3._Person_Singular": "regitur",
                "1._Person_Plural": "regimur",
                "2._Person_Plural": "regimini",
                "3._Person_Plural": "reguntur",
            },
            "konsonantische Konjugation Passiv Imperfekt": {
                "1._Person_Singular": "regebar",
                "2._Person_Singular": "regebaris",
                "3._Person_Singular": "regebatur",
                "1._Person_Plural": "regebamur",
                "2._Person_Plural": "regebamini",
                "3._Person_Plural": "regebantur",
            },
            "konsonantische Konjugation Passiv Perfekt": {
                "1._Person_Singular": "rectus sum",
                "2._Person_Singular": "rectus es",
                "3._Person_Singular": "rectus est",
                "1._Person_Plural": "recti sumus",
                "2._Person_Plural": "recti estis",
                "3._Person_Plural": "recti sunt",
            },
            "konsonantische Konjugation Passiv Plusquamperfekt": {
                "1._Person_Singular": "rectus eram",
                "2._Person_Singular": "rectus eras",
                "3._Person_Singular": "rectus erat",
                "1._Person_Plural": "recti eramus",
                "2._Person_Plural": "recti eratis",
                "3._Person_Plural": "recti erant",
            },
            "konsonantische Konjugation Passiv Futur 1": {
                "1._Person_Singular": "regar",
                "2._Person_Singular": "regeris",
                "3._Person_Singular": "regetur",
                "1._Person_Plural": "regemur",
                "2._Person_Plural": "regemini",
                "3._Person_Plural": "regentur",
            },
            "konsonantische Konjugation Passiv Futur 2": {
                "1._Person_Singular": "rectus ero",
                "2._Person_Singular": "rectus eris",
                "3._Person_Singular": "rectus erit",
                "1._Person_Plural": "recti erimus",
                "2._Person_Plural": "recti eritis",
                "3._Person_Plural": "recti erunt",
            },
            "konsonantische Konjugation Konjunktiv Präsens": {
                "1._Person_Singular": "regam",
                "2._Person_Singular": "regas",
                "3._Person_Singular": "regat",
                "1._Person_Plural": "regamus",
                "2._Person_Plural": "regatis",
                "3._Person_Plural": "regant",
            },
            "konsonantische Konjugation Konjunktiv Imperfekt": {
                "1._Person_Singular": "regerem",
                "2._Person_Singular": "regeres",
                "3._Person_Singular": "regeret",
                "1._Person_Plural": "regeremus",
                "2._Person_Plural": "regeretis",
                "3._Person_Plural": "regerent",
            },
            "konsonantische Konjugation Konjunktiv Perfekt": {
                "1._Person_Singular": "rexerim",
                "2._Person_Singular": "rexeris",
                "3._Person_Singular": "rexerit",
                "1._Person_Plural": "rexerimus",
                "2._Person_Plural": "rexeritis",
                "3._Person_Plural": "rexerint",
            },
            "konsonantische Konjugation Konjunktiv Plusquamperfekt": {
                "1._Person_Singular": "rexissem",
                "2._Person_Singular": "rexisses",
                "3._Person_Singular": "rexisset",
                "1._Person_Plural": "rexissemus",
                "2._Person_Plural": "rexissetis",
                "3._Person_Plural": "rexissent",
            },"konsonantische Konjugation Passiv Konjunktiv Präsens": {
                "1._Person_Singular": "regar",
                "2._Person_Singular": "regaris",
                "3._Person_Singular": "regatur",
                "1._Person_Plural": "regamur",
                "2._Person_Plural": "regamini",
                "3._Person_Plural": "regantur",
            },
            "konsonantische Konjugation Passiv Konjunktiv Imperfekt": {
                "1._Person_Singular": "regerer",
                "2._Person_Singular": "regereris",
                "3._Person_Singular": "regeretur",
                "1._Person_Plural": "regeremur",
                "2._Person_Plural": "regeremini",
                "3._Person_Plural": "regerentur",
            },
            "konsonantische Konjugation Passiv Konjunktiv Perfekt": {
                "1._Person_Singular": "rectus sim",
                "2._Person_Singular": "rectus sis",
                "3._Person_Singular": "rectus sit",
                "1._Person_Plural": "recti simus",
                "2._Person_Plural": "recti sitis",
                "3._Person_Plural": "recti sint",
            },
            "konsonantische Konjugation Passiv Konjunktiv Plusquamperfekt": {
                "1._Person_Singular": "rectus essem",
                "2._Person_Singular": "rectus esses",
                "3._Person_Singular": "rectus esset",
                "1._Person_Plural": "recti essemus",
                "2._Person_Plural": "recti essetis",
                "3._Person_Plural": "recti essent",
            },
            "gemischte Konjugation Präsens": {
                "1._Person_Singular": "capio",
                "2._Person_Singular": "capis",
                "3._Person_Singular": "capit",
                "1._Person_Plural": "capimus",
                "2._Person_Plural": "capitis",
                "3._Person_Plural": "capiunt",
            },
            "gemischte Konjugation Imperfekt": {
                "1._Person_Singular": "capiebam",
                "2._Person_Singular": "capiebas",
                "3._Person_Singular": "capiebat",
                "1._Person_Plural": "capiebamus",
                "2._Person_Plural": "capiebatis",
                "3._Person_Plural": "capiebant",
            },
            "gemischte Konjugation Plusquamperfekt": {
                "1._Person_Singular": "ceperam",
                "2._Person_Singular": "ceperas",
                "3._Person_Singular": "ceperat",
                "1._Person_Plural": "ceperamus",
                "2._Person_Plural": "ceperatis",
                "3._Person_Plural": "ceperant",
            },
            "gemischte Konjugation Perfekt": {
                "1._Person_Singular": "cepi",
                "2._Person_Singular": "cepisti",
                "3._Person_Singular": "cepit",
                "1._Person_Plural": "cepimus",
                "2._Person_Plural": "cepistis",
                "3._Person_Plural": "ceperunt",
            },
            "gemischte Konjugation Futur 1": {
                "1._Person_Singular": "capiam",
                "2._Person_Singular": "capies",
                "3._Person_Singular": "capiet",
                "1._Person_Plural": "capiemus",
                "2._Person_Plural": "capietis",
                "3._Person_Plural": "capient",
            },
            "gemischte Konjugation Futur 2": {
                "1._Person_Singular": "cepero",
                "2._Person_Singular": "ceperis",
                "3._Person_Singular": "ceperit",
                "1._Person_Plural": "ceperimus",
                "2._Person_Plural": "ceperitis",
                "3._Person_Plural": "ceperint",
            },
            "gemischte Konjugation Passiv Konjunktiv Präsens": {
                "1._Person_Singular": "capiar",
                "2._Person_Singular": "capiaris",
                "3._Person_Singular": "capiatur",
                "1._Person_Plural": "capiamur",
                "2._Person_Plural": "capiamini",
                "3._Person_Plural": "capiantur",
            },
            "gemischte Konjugation Passiv Konjunktiv Imperfekt": {
                "1._Person_Singular": "caperer",
                "2._Person_Singular": "capereris",
                "3._Person_Singular": "caperetur",
                "1._Person_Plural": "caperemur",
                "2._Person_Plural": "caperemini",
                "3._Person_Plural": "caperentur",
            },
            "gemischte Konjugation Passiv Konjunktiv Perfekt": {
                "1._Person_Singular": "captus sim",
                "2._Person_Singular": "captus sis",
                "3._Person_Singular": "captus sit",
                "1._Person_Plural": "capti simus",
                "2._Person_Plural": "capti sitis",
                "3._Person_Plural": "capti sint",
            },
            "gemischte Konjugation Passiv Konjunktiv Plusquamperfekt": {
                "1._Person_Singular": "captus essem",
                "2._Person_Singular": "captus esses",
                "3._Person_Singular": "captus esset",
                "1._Person_Plural": "capti essemus",
                "2._Person_Plural": "capti essetis",
                "3._Person_Plural": "capti essent",
            },
            "gemischte Konjugation PPA": {
                "Singular": "capiens",
                "Plural": "capientes",
            },
            "gemischte Konjugation PPP": {
                "Singular": "captus",
                "Plural": "capti",
            },
            "gemischte Konjugation PFA": {
                "Singular": "capturus",
                "Plural": "capturi",
            },
            "gemischte Konjugation Passiv Präsens": {
                "1._Person_Singular": "capior",
                "2._Person_Singular": "caperis",
                "3._Person_Singular": "capitur",
                "1._Person_Plural": "capimur",
                "2._Person_Plural": "capimini",
                "3._Person_Plural": "capiuntur",
            },
            "gemischte Konjugation Passiv Imperfekt": {
                "1._Person_Singular": "capiebar",
                "2._Person_Singular": "capiebaris",
                "3._Person_Singular": "capiebatur",
                "1._Person_Plural": "capiebamur",
                "2._Person_Plural": "capiebamini",
                "3._Person_Plural": "capiebantur",
            },
            "gemischte Konjugation Passiv Perfekt": {
                "1._Person_Singular": "captus sum",
                "2._Person_Singular": "captus es",
                "3._Person_Singular": "captus est",
                "1._Person_Plural": "capti sumus",
                "2._Person_Plural": "capti estis",
                "3._Person_Plural": "capti sunt",
            },
            "gemischte Konjugation Passiv Plusquamperfekt": {
                "1._Person_Singular": "captus eram",
                "2._Person_Singular": "captus eras",
                "3._Person_Singular": "captus erat",
                "1._Person_Plural": "capti eramus",
                "2._Person_Plural": "capti eratis",
                "3._Person_Plural": "capti erant",
            },
            "gemischte Konjugation Passiv Futur 1": {
                "1._Person_Singular": "capiar",
                "2._Person_Singular": "capieris",
                "3._Person_Singular": "capietur",
                "1._Person_Plural": "capiemur",
                "2._Person_Plural": "capiemini",
                "3._Person_Plural": "capientur",
            },
            "gemischte Konjugation Passiv Futur 2": {
                "1._Person_Singular": "captus ero",
                "2._Person_Singular": "captus eris",
                "3._Person_Singular": "captus erit",
                "1._Person_Plural": "capti erimus",
                "2._Person_Plural": "capti eritis",
                "3._Person_Plural": "capti erunt",
            },
            "gemischte Konjugation Konjunktiv Präsens": {
                "1._Person_Singular": "capiam",
                "2._Person_Singular": "capias",
                "3._Person_Singular": "capiat",
                "1._Person_Plural": "capiamus",
                "2._Person_Plural": "capiatis",
                "3._Person_Plural": "capiant",
            },
            "gemischte Konjugation Konjunktiv Imperfekt": {
                "1._Person_Singular": "caperem",
                "2._Person_Singular": "caperes",
                "3._Person_Singular": "caperet",
                "1._Person_Plural": "caperemus",
                "2._Person_Plural": "caperetis",
                "3._Person_Plural": "caperent",
            },
            "gemischte Konjugation Konjunktiv Perfekt": {
                "1._Person_Singular": "ceperim",
                "2._Person_Singular": "ceperis",
                "3._Person_Singular": "ceperit",
                "1._Person_Plural": "ceperimus",
                "2._Person_Plural": "ceperitis",
                "3._Person_Plural": "ceperint",
            },
            "gemischte Konjugation Konjunktiv Plusquamperfekt": {
                "1._Person_Singular": "cepissem",
                "2._Person_Singular": "cepisses",
                "3._Person_Singular": "cepisset",
                "1._Person_Plural": "cepissemus",
                "2._Person_Plural": "cepissetis",
                "3._Person_Plural": "cepissent",
            }
        }
        
        self.deklinationen_adjektive = {
            
        }
        
        self.hic_haec_hoc = {
            
        }
        
        self.qui_quae_qoud = {
            
        }
        
        self.ille_illa_illud = {
            
        }
        
        self.ipse_ipsa_ipsum = {
            
        }